### PR TITLE
fix: disable self-messaging

### LINKED ISSUE #31: Bad state: No element error when sender and recipient are the same!
I encountered the following error: **Unhandled Exception: Bad state: No element** at `package:xmtp/src/conversation/conversation_v2.dart:117:36`. After debugging, I discovered that this error occurs when the sender and recipient are the same. I believe that in this case assigning the sender or recipient directly to a peer could prevent this issue from occurring.

Full logs:-
`flutter: xmtp: <-- #007 /xmtp.message_api.v1.MessageApi/Query
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
#0      SetMixin.firstWhere (dart:collection/set.dart:236:5)
#1      ConversationManagerV2._conversationFromInvite (package:xmtp/src/conversation/conversation_v2.dart:117:36)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      ConversationManagerV2.listConversations (package:xmtp/src/conversation/conversation_v2.dart:91:25)
<asynchronous suspension>
#4      ConversationManager.listConversations (package:xmtp/src/conversation/manager.dart:63:19)
<asynchronous suspension>
#5      XmtpSession.refreshConversations (package:orb/component/xmtp/xmtp_session.dart:224:25)
<asynchronous suspension>
#6      XmtpSession._onListenConversations (package:orb/component/xmtp/xmtp_session.dart:244:5)
<asynchronous suspension>`

### PR DESCRIPTION
**Pull request by dmccartney**
This clarifies the error returned for #31

### CODE REVIEW

**Comment by neekolas** [comment]
Interesting timing. @jazzz is actually working to block self-messaging altogether in the js-SDK. 

So, we don't want to actually fix this bug. Just to throw a clearer error message ("sender and recipient address must be different"?)

**Review by saulmc — CHANGES_REQUESTED** [review]
@jazzz will be explicitly disabling self-messaging in the JS SDK based on @PranayAnchuri's risk assessment of self-DH

**Comment by nileshrathore** [comment]
If we want to disable self-messaging, the SDK must filter out conversations where the sender and recipient are the same and return the rest. Currently, the SDK is crashing and not returning any conversations in this case.

**Comment by dmccartney** [comment]
> If we want to disable self-messaging, the SDK must filter out conversations where the sender and recipient are the same and return the rest. Currently, the SDK is crashing and not returning any conversations in this case.

Yep, this PR should do both: prevent new self-conversations and also not-crash when a self-conversation shows up in the list.

**Comment by nileshrathore** [comment]
> > If we want to disable self-messaging, the SDK must filter out conversations where the sender and recipient are the same and return the rest. Currently, the SDK is crashing and not returning any conversations in this case.
> 
> Yep, this PR should do both: prevent new self-conversations and also not-crash when a self-conversation shows up in the list.

perfect! thanks!

**Review by elisealix22 — APPROVED** [review]
LGTM

**Pull request merged**
